export const metadata = {
  title: "Next.js app/app/(auth)/login",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    // <html lang="en">
    <div>{children}</div>
    // </html>
  );
}
